name: Run Python script at 10:30 UTC

on:
  schedule:
    # Runs every 5 minutes
    - cron: "40 10 * * *"
  workflow_dispatch:
jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.2"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run test.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python test.py
